//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Lebedeva3ISP11_16.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DishMenu()
        {
            this.MenuIngredient1 = new HashSet<MenuIngredient>();
            this.OrderMenu = new HashSet<OrderMenu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> PreparingTimeMin { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> MenuIngredientID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MenuIngredient MenuIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuIngredient> MenuIngredient1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenu> OrderMenu { get; set; }
    }
}
