//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Lebedeva3ISP11_16.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuIngredient
    {
        public int ID { get; set; }
        public int DishMenuID { get; set; }
        public Nullable<int> Ingredient1ID { get; set; }
        public Nullable<int> Ingredient2ID { get; set; }
        public Nullable<int> Ingredient3ID { get; set; }
        public Nullable<int> Ingredient4ID { get; set; }
        public Nullable<int> Ingredient5ID { get; set; }
        public Nullable<int> Ingredient6ID { get; set; }
    
        public virtual DishMenu DishMenu { get; set; }
        public virtual DishMenu DishMenu1 { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual Ingredient Ingredient1 { get; set; }
        public virtual Ingredient Ingredient2 { get; set; }
        public virtual Ingredient Ingredient3 { get; set; }
        public virtual Ingredient Ingredient4 { get; set; }
        public virtual Ingredient Ingredient5 { get; set; }
    }
}
