//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Lebedeva3ISP11_16.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderClient()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrderMenuID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<decimal> SumCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual OrderMenu OrderMenu { get; set; }
        public virtual Table Table { get; set; }
    }
}
