//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Lebedeva3ISP11_16.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int ID { get; set; }
        public int MenuID { get; set; }
        public int PersonalID { get; set; }
        public int ClientID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Clientt Clientt { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
