//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Lebedeva3ISP11_16.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int OrderMenuID { get; set; }
        public int PersonalID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int StatusID { get; set; }
    
        public virtual OrderMenu OrderMenu { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Status Status { get; set; }
    }
}
